### ISSUE TITLE
使用schnorr签名的TSS门限签名是只能模拟 n of n模式嘛？

### ISSUE THREAD

**Issue by GZK0329** [xuperchain/crypto#22]
TSS 使用schnorr签名的门限签名是只能模拟 n of n模式嘛？
一定要收集齐所有的签名碎片才能合成完整的？
要实现t of n （t < n）使用schnorr可以吗？还是必须使用BLS？
求指教

**Comment by HawkJing** [comment]
t of n （t < n）使用schnorr算法是可行的，开源代码库里已经包含了。具体调用方式请参考xchain_crypto_client.go。需要首先进行DKG过程，才能在签名收集的环节使用门限。另外，门限使用BLS好处是网络交互速度更快，缺点是你必须完全相信指定椭圆曲线的双线性映射的安全性。BLS门限的实现，后续代码整理后会开源出来。
